version: '3.8'

services:
  auth:
    build: ./auth
    ports:
      - '5000:5000'
    volumes:
      - ./auth:/app

  product:
    build: ./product
    ports:
      - '5001:5001'
    volumes:
      - ./product:/app
    depends_on:
      - auth

  order:
    build: ./order
    ports:
      - '5002:5002'
    volumes:
      - ./order:/app
    depends_on:
      - product
      - auth